### ISSUE TITLE
Which CEGUI version I need choose？

### ISSUE THREAD

**Issue by great90** [niello/ceed-cpp#22]
I add CEGUI v0.8.7 into the 3rdParty folder, but cannot find file 'CEGUI/UVector.h', 'CEGUI/USize.h', 'CEGUI/Sizef.h', 'CEGUI/HorizontalAlignment.h' and CEGUI/VerticalAlignment.h' when compile.

**Comment by vorlov-playrix** [comment]
You should use CEGUI master branch. CEGUI 0.8 is supported by old python-based ceed only.

**Comment by great90** [comment]
Thanks very much.
