### ISSUE TITLE
Change CEGUI project extension

### ISSUE THREAD

**Issue by vorlov-playrix** [niello/ceed-cpp#3]
'.project' extension is probably the worst possible one. It is long and it matches _any_ project. The probability is very high that someone chooses the same extension for completely different projects, so file associations will be messed up.
Good variant may be 'cegui' or 'ceed'. The latter is probably better because CEGUI doesn't know anything about projects.

**Comment by Ident** [comment]
Good point, and I would also vow for ".ceed"
